unfoldingWord/scripture-resources-rcl

coverage/shields.json
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/helpers.js

Should help address: https://github.com/unfoldingWord/gateway-language-translation-suite/issues/35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/3)

ParallelScripture: Handle missing verse

---

src/components/parallel-scripture/ParallelScripture.md
src/components/parallel-scripture/Row.js

Addresses https://github.com/unfoldingWord/gateway-language-translation-suite/issues/47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/4)

direction='auto'

---

src/components/parallel-scripture/ParallelScripture.md
src/core/selections/verseObjects.js

Addresses: https://github.com/unfoldingWord/gateway-language-translation-suite/issues/40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/5)

Fix for milestone rendering

---

src/components/parallel-scripture/ParallelScripture.md
src/core/selections/selections.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/6)

Fix For Whitespace Highlighting

---

src/components/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/16)

add export of license component

---

src/components/parallel-scripture/ScriptureTable.js
src/core/localStrings.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/27)

Collapsible Scripture Pane

---

src/components/parallel-scripture/ScriptureTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/28)

Max Height For Expanded Scripture

---

LICENSE
src/components/parallel-scripture/ParallelScripture.js
src/components/parallel-scripture/ParallelScripture.md
src/components/parallel-scripture/Row.js
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/helpers.js

I think this now pretty close to what we want - at least for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/26)

Feature klappy ranges

---

src/components/parallel-scripture/AddResourceMenu.js
src/components/parallel-scripture/ColumnsMenu.js
src/components/parallel-scripture/ParallelScripture.js
src/components/parallel-scripture/ParallelScripture.md
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/index.js
src/components/resources/Resource.context.js
src/components/resources/ResourceLinks.context.js
src/components/resources/Resources.context.js
src/components/resources/useResource.js
src/components/resources/useResources.js
src/core/localStrings.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/32)

Feature zach add resources

---

src/components/selections/helpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/35)

Fix Highlighting

---

src/components/parallel-scripture/ColumnsMenu.js
src/components/resources/resourcesHelper.js
src/components/resources/useResources.js
src/core/resources.js

fixes bug where invalid resource paths cause ParallelScripture component to crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/38)

Fixing bug found by @Birch in # 148 (PR # 37)

---

src/components/parallel-scripture/ParallelScripture.md
src/components/resources/useResources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/39)

Fix addresource bug when missing bookId 148

---

package.json
src/components/parallel-scripture/ColumnsMenu.js
src/components/parallel-scripture/ParallelScripture.js
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/helpers.js
src/components/resources/ResourceLinks.context.js
src/components/resources/Resources.context.js
src/components/resources/index.js
src/components/resources/useResource.js
src/components/resources/useResources.js
src/core/resources.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/45)

Early Fast Scrolling Fix

---

package.json
src/components/parallel-scripture/ParallelScripture.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/48)

Added Support For Open From Parent Component

---

package.json
src/components/parallel-scripture/ScriptureTable.js
src/components/verse-objects/AlignedWordsObject.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/52)

fixed ST propType for open; fixed data-test

---

package.json
src/components/parallel-scripture/ParallelScripture.md
src/core/resources.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/56)

Fix For Async function

---

src/components/resources/useResources.js
src/core/resources.js
src/core/resources.spec.js
src/core/selections/selections.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/63)

make add resource simpler

---

package.json
src/core/resources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/67)

filePath bug fix

---

package.json
src/components/resources/useRsrc.js
src/core/tsvToJson.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/68)

useRsrc now transforms TSV content into json objects 

---

package.json
src/components/resources/Resource.context.md
src/components/resources/useRsrc.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/73)

Feature/add option to return Bible JSON

---

package.json
src/components/resources/useRsrc.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/74)

BugFix/Fix issue of continuous resource fetching.

---

package.json
src/components/book/Book.js
src/components/parallel-scripture/ParallelScripture.js
src/components/parallel-scripture/ParallelScripture.md
src/components/parallel-scripture/ScriptureTable.js
src/components/selections/helpers.js
src/components/verse-objects/AlignedWordsObject.js
src/components/verse-objects/VerseObject.js
src/core/index.js

- Now exporting verse objects helper functions
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/77)

Fixes for quote highlighting in single-scripture-rcl

---

package.json
src/components/book/Book.js
src/components/book/Book.md
src/components/chapters/Chapter.js
src/components/chapters/Chapters.js
src/components/parallel-scripture/ColumnsMenu.js
src/components/reference/ReferenceSelectedContext.js
src/components/reference/useReferenceSelected.js
src/components/verses/Verse.js
src/components/verses/Verse.md
src/components/verses/Verses.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/85)

Merge zp cn 83 80 375  2

---

src/components/parallel-scripture/ColumnsMenu.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/80)

add close X to add resource menu

---

src/components/book/Book.js
src/components/book/Book.md
src/components/chapters/Chapter.js
src/components/chapters/Chapters.js
src/components/reference/ReferenceSelectedContext.js
src/components/reference/useReferenceSelected.js
src/components/verses/Verse.js
src/components/verses/Verse.md
src/components/verses/Verses.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/84)

BSA zach verse on click properties

---

src/components/verses/Verses.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/92)

Update demo, Verses.md

---

src/components/parallel-scripture/ColumnsMenu.js
src/components/resources/resourcesHelper.js
src/components/resources/useResources.js
src/core/localStrings.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/93)

Error handling for AddResource

---

src/core/localStrings.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/96)

Updated error message per QA fail

---

package.json
src/core/tsvToJson.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/103)

Fixed tsvToJson

---

package.json
src/core/resources.js
yarn.lock

- part of unfoldingWord/gateway-edit#130
- with PC network connected:
- disconnect PC from network (with WIFI connection it's easy to disable  WIFI for testing)
- connect to PC network
- disconnect PC from network
- connect PC to network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/106)

Feature 130/improve http error handling and add checking for network 

---

package.json
src/components/parallel-scripture/Row.js
src/components/verse-objects/AlignedWordsObject.js
src/components/verse-objects/MilestoneObject.js
src/components/verse-objects/OriginalWordObject.js
src/components/verse-objects/VerseObject.js
src/components/verse-objects/VerseObjects.js
src/components/verses/Verse.js
src/components/verses/Verses.js
src/core/index.js
src/core/lexiconHelpers.js
yarn.lock

- part of issue: https://github.com/unfoldingword/gateway-edit/issues/226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/118)

Feature 226/enhanced lexicon

---

package.json
src/components/parallel-scripture/ParallelScripture.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/scripture-resources-rcl/110)

autosave WIP

---

package.json
yarn.lock

Updated to new version usfm-js

---

package.json
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/helpers.js
src/components/verses/Verse.js
src/components/verses/Verses.js
src/components/verses/Verses.md

Feature cn 1151 hebrew font larger

---

package.json
src/components/parallel-scripture/helpers.js
src/components/verse-objects/MilestoneObject.js
src/components/verse-objects/VerseObject.js

- Verses with 'selah' within \qs should display the word and the highlight should work as well.
- https://github.com/unfoldingWord/tc-create-app/issues/1364

\qs tagged words in USFM

---

package.json
src/components/verses/Verse.js

- [ addresses the font size fix for ULT and UST]
- [Select a new testment file for eg-
en_tn_57-TIT.tsv
- need to check all font except greek.The screenshot is below
- 
]

Bugfix jincy 1151

---

package.json

updated the version

---

src/components/parallel-scripture/ParallelScripture.md
src/components/parallel-scripture/ScriptureTable.js
src/components/selections/Selections.context.js
src/components/selections/helpers.js
src/components/selections/useSelections.js
src/components/verse-objects/AlignedWordsObject.js
src/components/verse-objects/MilestoneObject.js
src/components/verse-objects/VerseObject.js
src/components/verse-objects/VerseObjects.js
src/components/verses/Verse.js

added ref and versemaps for highlighting

---

package.json

v5.3.6-beta.2

---

src/core/selections/selections.js

- [ Edge cases has been addressed for issue https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/gh/unfoldingword/tc-create-app/1491]
- [ in ParallelScripture for Quote use input ἡμῶν and Χριστῷ for testing the edgecases 1 and 2 correspondingly]

Edge cases has been addressed

---

package.json

- [ updated the release]
- [follow https://github.com/unfoldingWord/scripture-resources-rcl/pull/162 ]

added New Relase 5.3.7

---

package.json
src/core/selections/selections.js

- [ fixed QA fail for issue 1491 - the fix was for 1, 2, 3 etc occurences]
- [ change occurence number to 1, 2, 3 etc to see whether highlighting is done properly]

QA fail fixed for 1491

---

package.json
src/components/parallel-scripture/ParallelScripture.js
src/components/selections/useSelections.js
src/core/selections/selections.js

- part of https://github.com/unfoldingword/gateway-edit/issues/330

Feature 330 ampersand support

---

package.json
src/components/parallel-scripture/ParallelScripture.js
src/components/parallel-scripture/ParallelScripture.md
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/helpers.js
src/components/selections/Selections.context.js
src/components/selections/Selections.context.md
src/components/selections/helpers.js
src/components/selections/useSelections.js
yarn.lock

- Fixes highlighting issues found in tCC, described in issues: 1577 and 1580
- Use this parameters to test the highlighting:
{
params: {
name: "Middle word not being highlighted",
bookId: "PSA",
ref: "6:8-9",
quote: "יְ֝הוָ֗ה & יְ֭הוָה & יְ֝הוָ֗ה",
},
expected: "Yahweh & Yahweh & Yahweh",
},
{
params: {
name: "Testing deuteronomy highlighting error",
bookId: "DEU",
ref: "1:5-6",
quote: "מֹשֶׁ֔ה בֵּאֵ֛ר אֶת־הַ⁠תּוֹרָ֥ה הַ⁠זֹּ֖את לֵ⁠אמֹֽר׃ & יְהוָ֧ה אֱלֹהֵ֛י⁠נוּ דִּבֶּ֥ר אֵלֵ֖י⁠נוּ בְּ⁠חֹרֵ֣ב לֵ⁠אמֹ֑ר",
},
expected:
"Moses & explaining this law, saying & Yahweh our God spoke to us at Horeb, saying",
},

Bugfix 1577 1580 abelpz jincypjose

---

package.json
yarn.lock

updated uw-quote-helpers

---

src/components/parallel-scripture/ParallelScripture.js
src/components/parallel-scripture/ScriptureTable.js
src/components/parallel-scripture/ScriptureTable.md
src/components/parallel-scripture/helpers.js

- Used if it is a constant value named with All caps
Connected issue : https://github.com/unfoldingWord/scripture-resources-rcl/issues/174

updated the variable names

---

.npmignore
__tests__/fixtures/highlighting/tit/1-1-3.js
__tests__/greek-highlighting-helpers.spec.js
package.json
src/components/parallel-scripture/ParallelScripture.spec.js
src/components/selections/useSelections.js
src/components/verse-objects/AlignedWordsObject.js
src/core/selections/selections.js
src/core/selections/selections.spec.js
yarn.lock

- fixed highlighting for original language words using right quote characters
- fixed useEffect dependency and added more checks to make sure values are defined
- updated dependencies
- fixed unit tests
- also fixes https://github.com/unfoldingWord/gateway-edit/issues/534 - Selecti
- test with https://deploy-preview-604--gateway-edit.netlify.app
- in unfoldingword/en, navigate to Mat 12:30 - highlighting should work in all the tNotes
- if highlighting not showing initially, do refresh (added new issue for this bug)

Bugfix 570 / Fix highlighting errors with right quote in Greek Word

---

package.json
yarn.lock

Fix linefeed after whitespace

---

package.json
yarn.lock

bugfix/fix for \qs* end tag
